service_name: travis-pro
repo_token: k17wUNh1gXfbr5Clt82gpXvTRmmAQnFOU

[![Coverage Status](https://coveralls.io/repos/github/Moses-Omondi/PropertyPro-lite/badge.svg?branch=develop)](https://coveralls.io/github/Moses-Omondi/PropertyPro-lite?branch=develop)